#ifndef SURFACE_GOLDEN_CASES_HPP
#define SURFACE_GOLDEN_CASES_HPP

// Shared fixture types for tests/generated_surface_degree_reduction_cases.inc
// (generated by python_experiments/export_cpp_golden_cases.py). Include this
// header, then include the .inc inside your own (anonymous) namespace.

#include "surface_reduction_types.hpp"

#include <string>
#include <utility>
#include <vector>

struct SurfaceGolden
{
    int degree_u;
    int degree_v;
    int dim;
    std::vector<std::vector<std::vector<double>>> control_points;
    std::vector<std::vector<double>> weights;
    std::vector<double> knotvector_u;
    std::vector<double> knotvector_v;
};

struct SingleStepSurfaceSegmentGolden
{
    SurfaceGolden surface;
    double segment_error;
    std::pair<double, double> u_domain;
    std::pair<double, double> v_domain;
};

struct SingleStepSurfaceGoldenCase
{
    std::string name;
    SurfaceGolden input;
    double max_error;
    std::vector<SingleStepSurfaceSegmentGolden> segments;
};

inline mfem_raytracing::SurfaceData MakeSurfaceData(const SurfaceGolden &golden)
{
    mfem_raytracing::SurfaceData surface;
    surface.degree_u = golden.degree_u;
    surface.degree_v = golden.degree_v;
    surface.dim = golden.dim;
    surface.control_points = golden.control_points;
    surface.weights = golden.weights;
    surface.knotvector_u = golden.knotvector_u;
    surface.knotvector_v = golden.knotvector_v;
    surface.u_domain = {golden.knotvector_u[static_cast<std::size_t>(golden.degree_u)],
                        golden.knotvector_u[golden.knotvector_u.size() -
                                            static_cast<std::size_t>(golden.degree_u) - 1]};
    surface.v_domain = {golden.knotvector_v[static_cast<std::size_t>(golden.degree_v)],
                        golden.knotvector_v[golden.knotvector_v.size() -
                                            static_cast<std::size_t>(golden.degree_v) - 1]};
    return surface;
}

#endif
